In [1]:
import numpy

In [2]:
val=numpy.array([12,23,45,67,88])
print(val)

[12 23 45 67 88]


In [3]:
import numpy as np
val=np.array([12,23,45,67,89])
print(val)


[12 23 45 67 89]


In [4]:
from numpy import *
val=array([1,23,45,6,78,967])
print(val)

[  1  23  45   6  78 967]


In [5]:
# using array()
from numpy import *
val=array([12,23,45,67,89],int)
print(val)

[12 23 45 67 89]


In [6]:
from numpy import *
val=array([12,23,45,67,89],float)
print(val)

[12. 23. 45. 67. 89.]


In [8]:
from numpy import *
val=array([12,23,45.90,9,67,89])   # one float value but they are print all value float format
print(val)

[12.  23.  45.9  9.  67.  89. ]


In [9]:
char=array(['k','u','n','a','l'])
print(char)

['k' 'u' 'n' 'a' 'l']


In [10]:
str=array(["kunal","vicky","shivam","kaushal"])
print(str)

['kunal' 'vicky' 'shivam' 'kaushal']


In [13]:
a=array([1,2,3,4,5,6,7,8,9])
b=array(a)  # array()
c=a           # assing a to c
print(a,b,c)

[1 2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8 9]


In [15]:
# using linspace()
a=linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [16]:
a=linspace(0,10,6)  # 6 point
print(a)

[ 0.  2.  4.  6.  8. 10.]


In [17]:
a=linspace(0,10,7)
print(a)

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]


In [18]:
# logspace()
a=logspace(0,10,5)
print(a)

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]


In [19]:
# arange()
arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
arange(0,10,3)

array([0, 3, 6, 9])

In [22]:
arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [23]:
arange(0,10,1.5)

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [24]:
# even number up to 10
arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [25]:
# zeros and ones
zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
ones(10,float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
# bydefult data type is float
ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
# mathmatical operation
val=array([1,2,3,4,5,6,7,8,9])
val+=5
print(val)

[ 6  7  8  9 10 11 12 13 14]


In [32]:
# print element 10 to 15
a=arange(10,16)
print(a)

[10 11 12 13 14 15]


In [33]:
a[0]

10

In [35]:
a[1]

11

In [36]:
a[0:3]

array([10, 11, 12])

In [37]:
for i in a:
    print(i)

10
11
12
13
14
15


In [40]:
i = 0
while i < len(a):
    print(a[i])
    i += 1


10
11
12
13
14
15


In [41]:
a[0:5:2]

array([10, 12, 14])

In [42]:
a[0:5:3]

array([10, 13])

In [43]:
a[::]

array([10, 11, 12, 13, 14, 15])

In [44]:
a[0:]

array([10, 11, 12, 13, 14, 15])

In [45]:
a[:3]

array([10, 11, 12])

In [46]:
a[5:1:-1]

array([15, 14, 13, 12])

In [1]:
from numpy import *

In [2]:
arr=array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [4]:
val=array([[1,2,3,4],[1,2,3,4]])
print(val)

[[1 2 3 4]
 [1 2 3 4]]


In [5]:
val3=array([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]])
print(val3)

[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]


In [6]:
type(val3)

numpy.ndarray

In [8]:
val3.ndim   # dimenssion

3

In [9]:
val.ndim

2

In [10]:
val3.shape

(2, 2, 4)

In [11]:
print(val.shape)

(2, 4)


In [12]:
print(val3.shape)

(2, 2, 4)


In [14]:
# we can also change the shape 
val.shape=(4,2)

In [15]:
val

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [16]:
val3.shape=(4,2,2)

In [17]:
val3

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [18]:
val2=array([1,2,3,4,5,6])
print(val2)

[1 2 3 4 5 6]


In [19]:
val.size   # total no. of element

8

In [20]:
val2.size

6

In [21]:
val3.size

16

In [22]:
val.itemsize     # data type size

4

In [24]:
val2.itemsize

4

In [25]:
val3.itemsize

4

In [26]:
arr=([2.3,3.4,4.5,6.7])
print(arr)

[2.3, 3.4, 4.5, 6.7]


In [37]:
val1=array([2.3,2.3,4.5,6.7])
print(val1)

[2.3 2.3 4.5 6.7]


In [38]:
val1.shape

(4,)

In [39]:
val1.size

4

In [40]:
val1.itemsize

8

In [42]:
val1.dtype

dtype('float64')

In [43]:
val.dtype

dtype('int32')

In [44]:
val3.dtype

dtype('int32')

In [46]:
# nbyte given total no. of bytes occupied by array
# total no. of byte=size of array * item size of each element in array
val.nbytes

32

In [47]:
val3.nbytes

64

In [48]:
val1.nbytes

32

In [49]:
val2.nbytes

24

In [50]:
# reshape
val=arange(10)
val

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
val1=val.reshape(2,5)

In [56]:
val1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
val1=val.reshape(5,2)

In [58]:
val1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [60]:
# flatten : convert 2d to 1d
arr1=array([[1,2,3,4,6],[5,6,77,8,9]])
arr1.flatten()

array([ 1,  2,  3,  4,  6,  5,  6, 77,  8,  9])

In [61]:
# multiple dimenssion array
ones((4,6),int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [62]:
ones((5,6))   # bydefult float

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [63]:
zeros((4,6),int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [64]:
zeros((3,5),float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [65]:
# eye() create digonal
eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
a=eye(5,dtype=int)

In [74]:
for i in a:
    print(i)
     

[1 0 0 0 0]
[0 1 0 0 0]
[0 0 1 0 0]
[0 0 0 1 0]
[0 0 0 0 1]


In [75]:
a[0][1]

0

In [76]:
a[0][0]

1

In [77]:
a[1][1]

1

In [78]:
len(a)

5

In [79]:
a.shape

(5, 5)

In [81]:
a.itemsize

4

In [82]:
a.ndim

2

In [83]:
a.dtype

dtype('int32')

In [84]:
a.nbytes

100

In [85]:
a.flatten()

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1])

In [86]:
a.ndim

2

In [87]:
a.size

25

In [88]:
a=array([[1,2,3],[4,5,6],[7,8,9]])

In [89]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
a.ndim

2

In [92]:
for i in range(len(a)):
    print(i)

0
1
2


In [105]:
# display by the element 
for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j], end=' ')

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 5)

In [98]:
a=array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [99]:
a.ndim

3

In [103]:
for i in range(len(a)):
    for j in range(len(a[i])):
        for k in range(len(a[i][j])):
            print(a[i][j][k], end=' \t ')
        print()
    print()

1 	 2 	 3 	 
4 	 5 	 6 	 

1 	 2 	 3 	 
4 	 5 	 6 	 



In [106]:
# slicing in multiple dimenssion array
a=reshape(arange(11,36,1),(5,5))

In [107]:
a

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [110]:
a[0,:]  # 0 Rows

array([11, 12, 13, 14, 15])

In [114]:
a[:,0]  # o column

array([11, 16, 21, 26, 31])

In [115]:
a[1:2,1:2]

array([[17]])

In [116]:
# all row 1st column
a[0:5,1:2]

array([[12],
       [17],
       [22],
       [27],
       [32]])

In [117]:
a[0:2,0:3]

array([[11, 12, 13],
       [16, 17, 18]])

In [118]:
a[2:4,3:5]

array([[24, 25],
       [29, 30]])

In [119]:
# matrix
# matrix_name=matrix(2d array or string)
arr=[[1,2,3],[4,5,6]]
m=matrix(arr)

In [120]:
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [121]:
# another method
arr=matrix([[1,2,3],[4,5,6]])
arr

matrix([[1, 2, 3],
        [4, 5, 6]])

In [123]:
# another matrix
str='1 2; 3 4; 5 6'
m1=matrix(str)

In [124]:
m1

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [128]:
m1=matrix('1,2,3; 4 5 6; 7 8 9')

In [129]:
m1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [130]:
# find the digonal
a=diagonal(m1)

In [131]:
a

array([1, 5, 9])

In [132]:
m1.max()

9

In [133]:
m1.min()

1

In [134]:
m1.sum()

45

In [135]:
m1.mean()

5.0

In [137]:
 m1.prod(0)

matrix([[ 28,  80, 162]])

In [138]:
m1.prod(1)

matrix([[  6],
        [120],
        [504]])

In [140]:
sort(m1)

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [141]:
val=matrix([[3,1,9],[1,7,3]])
a=sort(val)

In [142]:
a

matrix([[1, 3, 9],
        [1, 3, 7]])

In [143]:
sort(a,axis=0) # columan wise

matrix([[1, 3, 7],
        [1, 3, 9]])

In [144]:
sort(a,axis=1)

matrix([[1, 3, 9],
        [1, 3, 7]])

In [145]:
m1=matrix('1,2,3; 4 5 6; 7 8 9')
# transpose matrix


In [146]:
m1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [147]:
t=m.transpose()

In [148]:
t

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [149]:
t1=m.getT()

In [150]:
t1

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [156]:
# write a program accept the keyword and dispaly the transpose matrix
r,c=[int(x) for x in input("enter the row and column: ").split()]
str=input("enter the matrix element : ")
val=reshape(matrix(str),(r,c))
print(val)

print("after transposition value is : ")
m=val.transpose()
print(m)

enter the row and column:  2 3
enter the matrix element :  1 2 3 4 5 6 


[[1 2 3]
 [4 5 6]]
after transposition value is : 
[[1 4]
 [2 5]
 [3 6]]


In [157]:
m=val.getT()

In [158]:
m

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [161]:
a=matrix('1 2 3; 4 5 6')
b=matrix('9 8 7; 6 5 4')
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[9 8 7]
 [6 5 4]]


In [162]:
# add
c=a+b
print(c)

[[10 10 10]
 [10 10 10]]


In [163]:
# sub 
d=a-b
print(d)

[[-8 -6 -4]
 [-2  0  2]]


In [164]:
# div
e=c/b
print(e)

[[1.11111111 1.25       1.42857143]
 [1.66666667 2.         2.5       ]]


In [165]:
f=matrix([[1,2],[3,4],[5,6]])
f

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [166]:
g=a*f

In [167]:
g

matrix([[22, 28],
        [49, 64]])

In [168]:
import sys

In [170]:
r1,c1=[int(a) for a in input("enter the row and column : ").split()]
r2,c2=[int(a) for a in input("enter the row and column : ").split()]
if c1!=r2:
    print("multiplication is not possible ")
    sys.exit()

str1=input("enter the 1st matrix elemnt : ")
val=reshape(matrix(str1),(r1,c1))

str2=input("enter the 2nd matrix element : ")
val2=reshape(matrix(str2),(r2,c2))

val3=val * val2
print("the product matrix is : {} ".format(val3))

enter the row and column :  2 3
enter the row and column :  3 2
enter the 1st matrix elemnt :  1 2 3 4 5 6
enter the 2nd matrix element :  1 0 0 2 1 3


the product matrix is : [[ 4 13]
 [10 28]] 


In [171]:
# random number
random.rand()

0.2467357016006715

In [172]:
a=random.rand(5)

In [173]:
a

array([0.78964178, 0.64688386, 0.87051878, 0.75116272, 0.25426381])

In [174]:
b=random.rand(2,3)

In [175]:
b

array([[0.34141571, 0.89057561, 0.51244601],
       [0.8344769 , 0.33518825, 0.31292047]])

In [176]:
random.randint(10,20)

18

In [179]:
random.random_sample(5)  #0.0 to 1.0

array([0.87358453, 0.50952188, 0.48418618, 0.08539059, 0.39268592])